# Docker file to build E2E environment
version: '3'

services:

  jenkins:
    build: Jenkins/
    volumes:
      - ./Jenkins/jcasc_config.yml:/var/jenkins_home/jenkins.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    user: root
    networks:
      - local_net
    ports:
      - "8080:8080"
      - "50000:50000"

  sonarqube:
    image: sonarqube:lts
    depends_on:
      - jenkins
    networks:
      - local_net
    ports:
      - "9000:9000"

networks:
  local_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.6.0/24